"use client";

import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Download, Loader2 } from "lucide-react";
import type { AnalysisResult } from "@/lib/agents/types";
import type { AgentConfig } from "@/lib/agents/types";

interface ExportButtonProps {
  result: AnalysisResult;
  agent: AgentConfig;
  title: string;
  createdAt: string;
  inputText?: string;
}

export function ExportButton({
  result,
  agent,
  title,
  createdAt,
  inputText,
}: ExportButtonProps) {
  const [exporting, setExporting] = useState(false);

  async function handleExport() {
    setExporting(true);
    try {
      const content = generateMarkdownReport({
        result,
        agent,
        title,
        createdAt,
        inputText,
      });

      // Create a Blob and trigger download
      const blob = new Blob([content], { type: "text/markdown;charset=utf-8" });
      const url = URL.createObjectURL(blob);
      const link = document.createElement("a");
      link.href = url;
      link.download = `${sanitizeFilename(title)}-analysis.md`;
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      URL.revokeObjectURL(url);
    } finally {
      setExporting(false);
    }
  }

  return (
    <Button
      variant="outline"
      size="sm"
      onClick={handleExport}
      disabled={exporting}
      className="gap-2"
    >
      {exporting ? (
        <Loader2 className="h-3.5 w-3.5 animate-spin" />
      ) : (
        <Download className="h-3.5 w-3.5" />
      )}
      Export
    </Button>
  );
}

function sanitizeFilename(name: string): string {
  return name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "")
    .slice(0, 50);
}

function generateMarkdownReport({
  result,
  agent,
  title,
  createdAt,
  inputText,
}: {
  result: AnalysisResult;
  agent: AgentConfig;
  title: string;
  createdAt: string;
  inputText?: string;
}): string {
  const date = new Date(createdAt).toLocaleString();
  const lines: string[] = [];

  lines.push(`# ${title}`);
  lines.push("");
  lines.push(`**Agent:** ${agent.icon} ${agent.name}`);
  lines.push(`**Date:** ${date}`);
  lines.push(`**Overall Score:** ${result.score}/100`);
  lines.push("");
  lines.push("---");
  lines.push("");

  // Summary
  lines.push("## Summary");
  lines.push("");
  lines.push(result.summary);
  lines.push("");

  // Score Breakdown
  if (result.details && typeof result.details === "object") {
    const scores = extractScores(result.details);
    if (scores.length > 0) {
      lines.push("## Score Breakdown");
      lines.push("");
      lines.push("| Category | Score |");
      lines.push("|----------|-------|");
      for (const s of scores) {
        lines.push(`| ${s.label} | ${s.score}/100 |`);
      }
      lines.push("");
    }
  }

  // Flags
  if (result.flags && result.flags.length > 0) {
    lines.push("## Issues Found");
    lines.push("");
    for (const flag of result.flags) {
      const icon =
        flag.severity === "critical"
          ? "🔴"
          : flag.severity === "warning"
            ? "🟡"
            : "🔵";
      lines.push(`${icon} **[${flag.severity.toUpperCase()}]** ${flag.message}`);
      if (flag.context) {
        lines.push(`   > "${flag.context}"`);
      }
      lines.push("");
    }
  }

  // Suggestions
  if (result.suggestions && result.suggestions.length > 0) {
    lines.push("## Recommendations");
    lines.push("");
    for (let i = 0; i < result.suggestions.length; i++) {
      lines.push(`${i + 1}. ${result.suggestions[i]}`);
    }
    lines.push("");
  }

  // Rewrite
  if (result.rewrite) {
    lines.push("## Improved Version");
    lines.push("");
    lines.push("```");
    lines.push(result.rewrite);
    lines.push("```");
    lines.push("");
  }

  // Original input
  if (inputText) {
    lines.push("---");
    lines.push("");
    lines.push("## Original Input");
    lines.push("");
    lines.push("```");
    lines.push(inputText.slice(0, 2000));
    if (inputText.length > 2000) {
      lines.push(`\n... (${inputText.length - 2000} more characters)`);
    }
    lines.push("```");
    lines.push("");
  }

  lines.push("---");
  lines.push(`*Generated by AgentDesk — ${agent.name} Agent*`);

  return lines.join("\n");
}

function extractScores(
  details: Record<string, unknown>
): Array<{ label: string; score: number }> {
  const scores: Array<{ label: string; score: number }> = [];
  for (const [key, value] of Object.entries(details)) {
    if (
      value &&
      typeof value === "object" &&
      "score" in (value as Record<string, unknown>)
    ) {
      const detail = value as Record<string, unknown>;
      if (typeof detail.score === "number") {
        scores.push({
          label: key.replace(/_/g, " ").replace(/\b\w/g, (c) => c.toUpperCase()),
          score: detail.score,
        });
      }
    }
  }
  return scores;
}
